### PR TITLE
Os 128 fixes

### PR DESCRIPTION
**Pull request by lintong-zhang**
we have verified that lidar undistortion package works with os-128. Unit test with pcd files are added as well. 

the detailed issue with vilens integration is at https://github.com/ori-drs/vilens/issues/411

For the unit test, visualiation is here. The processed pc is perfectly aligned with undistorted pc. 

image

### CODE REVIEW

**Comment by mcamurri** [comment]
The PR is good but the function name `convertQuant2RotMatrix` is misleading. It is converting to a pose not a rotation matrix.
Can you call it `posQuatToEigenIsometry` or something like that.

**Comment by lintong-zhang** [comment]
@mcamurri  can i merge and close this now?

**Comment by mcamurri** [comment]
yes I'll merge it

**Comment by lintong-zhang** [comment]
[jenkins test this]

**Review by mcamurri — APPROVED** [review]

**Comment by mcamurri** [comment]
[jenkins test this]

**Pull request merged**
