### PR TITLE
remove the two node handles, add point_cloud_topic parameter

### PR DESCRIPTION
**Pull request by mcamurri**
Not fully tested yet. Requested by @mauricefallon in https://github.com/ori-drs/drs_base/issues/343

### CODE REVIEW

**Comment by mauricefallon** [comment]
you've changed this so the input topic is read from a param.
But the output topic has to be remapped.

why not have both input and output topics be remapped?

**Comment by mcamurri** [comment]
I prefer parameters because they can be loaded from yaml and they can be inspected from the parameter server at any time. 

Remapping topics instead can be done only in launchfiles and you need to interrogate the node to understand what it is subscribing/ publishing to. 

I will put also the output topic as parameter and set it to your defaults, so no remapping or extra parameters are needed on your side.

It has to be noted though that using `/os_cloud_node/points_corrected` as the output topic name induces to believe that the topic is produced by the `os_cloud_node` (i.e. the ouster driver) while effectively it is advertised by the `lidar_undistortion` package.

**Comment by mauricefallon** [comment]
> It has to be noted though that using /os_cloud_node/points_corrected as the output topic name induces to believe that the 
> topic is produced by the os_cloud_node (i.e. the ouster driver) while effectively it is advertised by the lidar_undistortion package.

I guess we should just use "/lidar/points" and  "/lidar/points_corrected" but its a little late for that now.

**Comment by mcamurri** [comment]
if the ouster driver advertises the point cloud in `/os_cloud_node/points`, the input topic has to be named that way, it can't be `/lidar/points` unless you change the ouster driver to behave that way. 

But even then, you would have the same problem as before: if don't know who makes `/lidar/points`, you have to inspect with `rosopic info` to find out, as opposed to just reading the topic name.

With the parameters, you have of course the freedom to choose, but what is the main reason for the corrected topic to have the same namespace as the input topic?  They are (and will probably always be) produced by two different nodes.

**Comment by mcamurri** [comment]
With the above commit, the intended behavior for the spot launchfile would be achieved by using this code:
```
<launch>
    <node name="lidar_undistortion" pkg="lidar_undistortion_ros" type="ouster_undistortion_node" output="screen">
        <param name="point_cloud_input_topic" value="/os_cloud_node/points" />
        <param name="point_cloud_output_topic" value="/os_cloud_node/points_corrected" />
        <param name="pose_topic" value="/spot/pose" />
        <param name="base_frame_id" value="body" />
        <param name="fixed_frame_id" value="odom" />
        <param name="lidar_frame_id" value="os_sensor" />
        <param name="ouster_config_file" value="$(find lidar_undistortion)/config/os0_64_gen2_fw_114b12_sn_102032000876.json" />
    </node>
</launch>
```
The first two params can actually be omitted, but I've included them for completeness.

Alternatively, you can just have the following yaml...
```
fixed_frame_id: "odom"
base_frame_id: "body"
pose_topic: "/spot/pose"
point_cloud_input_topic : "/os_cloud_node/points"
point_cloud_output_topic: "/os_cloud_node/points_corrected"
lidar_frame_id: "os_sensor"
ouster_config_file: "$(find lidar_undistortion)/config/os0_64_gen2_fw_114b12_sn_102032000876.json"
```
... and then run the boiler plate code for the launchfile:
```
<launch>
  <node name="spot_lidar_undistortion" pkg="lidar_undistortion_ros" type="ouster_undistortion_node" output="screen">
    <rosparam command="load" file="$(find spot_runtime_drs)/config/undistortion.yaml" subst_value="true" />
</launch>
```
assuming the yaml is placed under `spot_runtime_drs/config/undistortion.yaml`

**Comment by mauricefallon** [comment]
thanks, I've tested and committed the launch file to the spot repo:
https://github.com/ori-drs/spot_runtime_drs/pull/7/commits/b7ddbbdee2031fa6b799b5b9e19936e2f6893bdf

feel free to merge this PR

**Pull request merged**
