### PR TITLE
remove dependency on velodyne_pointcloud

### LINKED ISSUE #18: Implicit dependency on velodyne_pointcloud package
When @mcamurri and I did some testing on ANYmal on Friday we noticed that vilens didn't work with the `/velodyne_packets` topic. It did previously before the upgrade.

At the time we thought that this didn't work since ANYbotics have defined their own custom Velodyne ros message type, `any_velodyne_msgs`, which defined exactly the same as the standard `velodyne_msgs`.  To test this I made a small conversion node between the two message types (pushed to `feature/anybotics-to-standard-velo-msg-converter` branch of `anymal_logging_drs`). However, this wasn't the problem and vilens could subscribe to both message types correctly - probably because they are defined exactly the same.

After further investigation, it failed because we didn't have the `velodyne_pointcloud` package installed by default. The `VelodyneScanConverter` implicitly relies on this package if the [rosparams do not point to a particular calibration file](https://github.com/ori-drs/lidar_undistortion/blob/2a0d0b0f39e81d8cfc3511b318ee6ef3eba6a23f/lidar_undistortion_ros/include/lidar_undistortion_ros/velodyne_scan_converter.hpp#L58). Therefore the scan converter wasn't able to load its parameters and didn't convert any points.

@mcamurri - what do you think is the best way to resolve this? Maybe make it point to a calibration file in `lidar_undistortion_ros` and fail if it can't find one?

### PR DESCRIPTION
**Pull request by mcamurri**
To be independent from the version of the velodyne driver, I've copied some files in. However, the include guards must have created a name clash that I can solve by using the `#pragma once` directive instead.

This error occurred on my laptop but not on the build server, probably because it is dependent on what version of the velodyne drivers are installed

### CODE REVIEW

**Comment by mcamurri** [comment]
[jenkins test this]

**Comment by dwisth** [comment]
My main problem still exists that if the config file in `velodyne_pointcloud` can't be found then it doesn't convert from velodyne packets to point cloud (it just silently fails).

So either we need it to point to a different config file by default, or throw an error if it can't load the config.

**Comment by mcamurri** [comment]
These last commits should fix that, sorry I didn't spot this before.

**Comment by mcamurri** [comment]
You think we can merge this, @dwisth ? The server succeded.

**Pull request merged**
